CFLAGS=/nologo /W4 /EHsc /Za /DDEBUG__=1

main.exe: main.obj add.obj
	cl $(CFLAGS) main.obj add.obj

main.obj: main.c
	cl $(CFLAGS) /c main.c
	
add.obj: add.c
	cl $(CFLAGS) /c add.c

clean:
	del *.obj *.exe
